
# docker compose version
version: '3.8'

services:
  
  # frontend service
  web:
    # start api before web
    depends_on:
      - api
    
    # location of Dockerfile
    build: ./frontend
    command: ng serve --host 0.0.0.0 --port ${DOCKER_CLIENT_PORT_FORWARD}
    ports: 
      - ${CLIENT_PORT}:${DOCKER_CLIENT_PORT_FORWARD}
    environment:
      BASE_API_URL: http://${SERVER_IP}:${DOCKER_SERVER_PORT_FORWARD}/api/v1
    env_file:
      - .env

    # stuff for docker watch
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend/angular.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync


  # backend service
  api:
    depends_on:
      - db
    build: ./backend
    command: python manage.py runserver 0.0.0.0:${DOCKER_SERVER_PORT_FORWARD}
    ports:
      - ${SERVER_PORT}:${DOCKER_SERVER_PORT_FORWARD}
    image: django-docker:0.0.1
    environment:
      - DB_URL=mongodb://db/plant
    env_file:
      - .env

    develop:
      watch:
      - path: ./backend/requirements.txt
        action: rebuild
      - path: ./backend
        target: /app
        action: sync


  db:
    image: postgres:16-bookworm
    volumes:
      - plant:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  plant: